# A config to get an MCMC chain started.  This runs a job with 1M steps.

fitterEngineConfig:

  minimizerConfig:
    type: SimpleMcmc
    algorithm: metropolis
    proposal: adaptive
    # Make sure that MinimizerBase doesn't get involved.
    checkParameterValidity: true
    # The validity that SimpleMcmc needs to check.
    likelihoodValidity: range,physical,nomirror
    # No restoration by default.  Usually overridden from the command line
    adaptiveRestore: none

    cycles: 5
    steps: 10000
    acceptanceWindow: 400
    covarianceWindow: 200000
    covarianceDeweighting: 0.0
    sequence: |
      for (int chain = 0; chain < gMCMC.Cycles(); ++chain) {
        std::cout << "Start chain " << chain << std::endl;
        gMCMC.RunCycle("Chain",chain);
      }
